-d D:\File\Micky\Github\T-FPGA\example\FPGA\spi-blink\impl\gwsynthesis\spi-blink.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\File\Micky\Github\T-FPGA\example\FPGA\spi-blink\src\spi-blink.cst
-cfg D:\File\Micky\Github\T-FPGA\example\FPGA\spi-blink\impl\pnr\device.cfg
-sdc D:\File\Micky\Github\T-FPGA\example\FPGA\spi-blink\src\spi-blink.sdc
-bit
-tr
-ph
-timing
-cst_error
