-d D:\Users\19021\Documents\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\Users\19021\Documents\fpga_project\src\fpga_project.cst
-cfg D:\Users\19021\Documents\fpga_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
